### ISSUE TITLE
CSS transitions on sorting

### ISSUE THREAD

**Issue by pkese** [alfonsogarciacaro/Lit.TodoMVC#1]
Hi. 

The demo at https://alfonsogarciacaro.github.io/Lit.TodoMVC/ has a checkbox for sorting the list
and includes these nice CSS transitions when the list is reordered.

Is there any chance to see that code as well ... I couldn't find that checkbox in the code in this repo.

Btw, I just got myself acquainted with Lit and already love it 100% (also, thanks for the library and the posts ).

To learn Lit, I adopted your demo from Elmish to [FSharp.Data.Adaptive](https://github.com/fsprojects/FSharp.Data.Adaptive) and it was absolutely fantastic, how easy it was to define Hooks for Adaptive... 
All that was needed was this: https://github.com/pkese/Lit.Adaptive.TodoMVC/blob/main/src/Util.fs#L20

I have a business data visualization app built with Adaptive and I really appreciate the fact that Adaptive updates the state tree lazily (/i.e. selectively): if some components are not mounted, the part of the state tree linking to those components will remain dark and won't get updated at all.   
(I think that other state libraries based on Observables simply render full state each time).

So now I can port my old code from React and Fable.Elmish.Adaptive to Lit with these cool Hooks.
(Adaptive will need a few trivial fixes on upstream to get it compatible with Fable 3 though).

**Comment by alfonsogarciacaro** [comment]
Hi @pkese! Happy that you like Fable.Lit 💟 

The animation when sorting is done by [lit's animate directive](https://www.npmjs.com/package/@lit-labs/motion) but it seems this is only compatible with Lit Elements so I had to wrap everything in a LitElement, but with `useShadowDom` set to false so we can still use global rules like Bulma. I just merged the PR to do that, can you please pull the changes and try again? (You'll have to run `npm install` again).

> (I think that other state libraries based on Observables simply render full state each time).

Sutil is based on observables but if I remember correctly the bindings keep the previous value so they won't re-render when receiving pushes unless it's a new value.

**Comment by pkese** [comment]
Thanks.

The idea with Adaptive is that you can even apply Lit rendering to the state and have `aval<Lit.TemplateResult>` inside the adaptive state. And still everything (even the dependent state that's in the middle of the graph) gets evaluated only if the components are mounted.

The way that I see it is that:
- Observables are a directed graph getting evaluated in cascade when state changes (but propagation is stopped when in case new value equals current value),
- whereas in Adaptive, the state inside the graph gets evaluated only if someone is actively listening on the other side. Even if state had changed (e.g. a todo being added to the list), the next steps (list getting sorted, then sorted list getting rendered) won't get evaluated and state won't get propagated further, unless someone is registered as a listener (i.e. end components being mounted on page).

Please correct me if I'm wrong.

I've made a demo with a pipeline:  
`cval<todos> -> aval<sorted todos> -> aval<todos TemplateResult> -> {Lit.render if boolean displayTodos = true}`  
to show that sorting won't happen unless components are mounted.
https://github.com/pkese/Lit.Adaptive.TodoMVC/blob/580b549b3ac910d47ecb038fe4f7c2c5cd913963/src/App.fs#L153

This is quite a big deal if evaluation is expensive in case of heavy state-data processing or when propagating state updates requires data from server (in my case I need both).

**Comment by pkese** [comment]
The demo with `useShadowDom` is very valuable. I probably wouldn't be able to figure that out myself. 🙏

**Comment by pkese** [comment]
Note to myself...

We'll probably need some bindings for (or equivalent of) https://github.com/PolymerLabs/uni-virtualizer and appropriate adaptive wrapper component to turn `alist<Lit.TemplateResult>` into infinite virtual scroll, before people really understand the power of Adaptive's declarative state and lazy evaluation.

E.g. an example declarative Twitter app:

```fsharp
let tweetIds = cval [ _thousands; _of; _tweet; _ids ]

let html =
    tweetIds
    |> AList.map fetchDataFromServer
    |> AList.map renderHtmlTemplate
    |> Lit.adaptiveVirtualScroll
```    
... and observe how tweets get dynamically loaded and updated only as you scroll down the page.

**Comment by pkese** [comment]
Closing this, since #2 fixed the issue. Thanks.

**Comment by alfonsogarciacaro** [comment]
> We'll probably need some bindings for uni-virtualizer

Here you go :) #3 

This requires latest fable so make sure to update tools & dependencies for testing, you can just use `npm install` for that:

```
git pull
git checkout virtualizer
npm install
npm start
```

Bindings [are here](https://github.com/alfonsogarciacaro/Lit.TodoMVC/pull/3/files#diff-08382058c2ea796fdadf243b6fefc8d1157db9ee99a9d36e52bd1124002cd2a3). It seems lit-virtualizer is not about infinite scrolling because it asks you to pass the whole array of items, but maybe you can listen to the [rangeChange event](https://www.npmjs.com/package/lit-virtualizer#rangechange-event) and send a request when scroll is close to the end.

**Comment by pkese** [comment]
Gee, thanks. This was beyond my expectations :-)
